# Generated by Django 2.2.10 on 2020-04-11 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDownTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название оборудования')),
            ],
            options={
                'verbose_name': 'Объект простоя',
                'verbose_name_plural': 'Объекты простоя',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeDownTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, verbose_name='Название простоя')),
                ('order', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Тип простоя',
                'verbose_name_plural': 'Типы простоя',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkDownTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата работ')),
                ('comment_one', models.CharField(max_length=1000, verbose_name='Комментарий к работам в 1 смену')),
                ('comment_two', models.CharField(max_length=1000, verbose_name='Комментарий к работам в 2 смену')),
            ],
            options={
                'verbose_name': 'Производимые работы',
                'verbose_name_plural': 'Производимые работы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DownTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата')),
                ('amount', models.TimeField(verbose_name='Время простоя')),
                ('type_downtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dt.TypeDownTime', verbose_name='Тип простоя')),
            ],
            options={
                'verbose_name': 'Простои',
                'verbose_name_plural': 'Простои',
                'ordering': ['-date'],
            },
        ),
    ]
