# Generated by Django 2.2.10 on 2020-04-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0003_workdowntime_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdowntime',
            name='comment_one',
            field=models.CharField(default='', max_length=1000, verbose_name='Комментарий к работам в 1 смену'),
        ),
        migrations.AlterField(
            model_name='workdowntime',
            name='comment_two',
            field=models.CharField(default='', max_length=1000, verbose_name='Комментарий к работам в 2 смену'),
        ),
    ]
