# Generated by Django 2.2.10 on 2020-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0005_auto_20200412_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='smena',
            field=models.NullBooleanField(),
        ),
    ]
