# Generated by Django 2.2.10 on 2020-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0006_downtime_smena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='smena',
            field=models.BooleanField(choices=[(1, '1 смена'), (2, '2 смена')], default=1, verbose_name='Смена'),
        ),
    ]
