# Generated by Django 2.2.10 on 2020-04-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0008_auto_20200412_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtime',
            options={'verbose_name': 'Простои', 'verbose_name_plural': 'Простои'},
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='smena',
        ),
        migrations.AddField(
            model_name='workdowntime',
            name='smena_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smena1', to='dt.DownTime', verbose_name='Простои в 1 смену'),
        ),
        migrations.AddField(
            model_name='workdowntime',
            name='smena_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smena2', to='dt.DownTime', verbose_name='Простои в 2 смену'),
        ),
    ]
