# Generated by Django 2.2.10 on 2020-04-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0011_auto_20200418_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtime',
            options={'ordering': ['-work'], 'verbose_name': 'Простои', 'verbose_name_plural': 'Простои'},
        ),
        migrations.AlterField(
            model_name='downtime',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='dt.Work', verbose_name='Работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dt.ObjectDownTime', unique_for_date='date', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.ManyToManyField(through='dt.DownTime', to='dt.TypeDownTime'),
        ),
    ]
