# Generated by Django 2.2.10 on 2020-04-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0012_auto_20200423_2027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downtime',
            unique_together={('work', 'type', 'smena')},
        ),
    ]
